module.exports = {
  b3: [
    ["PETR4", "Petrobras PN"],
    ["PETR3", "Petrobras ON"],
    ["VALE3", "Vale"],
    ["ITUB4", "Itaú Unibanco PN"],
    ["ITUB3", "Itaú Unibanco ON"],
    ["BBDC4", "Bradesco PN"],
    ["BBDC3", "Bradesco ON"],
    ["BBAS3", "Banco do Brasil"],
    ["SANB11", "Santander Units"],
    ["ABEV3", "Ambev"],
    ["WEGE3", "WEG"],
    ["ITSA4", "Itaúsa"],
    ["MGLU3", "Magazine Luiza"],
    ["LREN3", "Lojas Renner"],
    ["B3SA3", "B3"],
    ["BPAC11", "BTG Pactual Units"],
    ["VIVT3", "Telefônica Vivo"],
    ["CMIG4", "Cemig PN"],
    ["ELET3", "Eletrobras ON"],
    ["ELET6", "Eletrobras PNB"],
    ["SUZB3", "Suzano"],
    ["JBSS3", "JBS"],
    ["BRFS3", "BRF"],
    ["KLBN11", "Klabin Units"],
    ["GGBR4", "Gerdau PN"],
    ["CSNA3", "CSN"],
    ["USIM5", "Usiminas PNA"],
    ["RENT3", "Localiza"],
    ["VBBR3", "Vibra Energia"],
    ["RAIZ4", "Raízen"],
    ["PRIO3", "PetroRio"],
    ["HAPV3", "Hapvida"],
    ["RDOR3", "Rede D'Or"],
    ["TOTS3", "Totvs"],
    ["LWSA3", "Locaweb"],
    ["CASH3", "Méliuz"],
    ["POSI3", "Positivo"],
    ["ENGI11", "Energisa Units"],
    ["EQTL3", "Equatorial"],
    ["RADL3", "RaiaDrogasil"],
    ["ASAI3", "Assaí"],
    ["CCRO3", "CCR"],
    ["AMER3", "Americanas"],
    ["AZUL4", "Azul PN"],
    ["GOLL4", "GOL PN"],
    ["EMBR3", "Embraer"],
    ["CYRE3", "Cyrela"],
    ["MRVE3", "MRV"],
    ["EZTC3", "EZTec"],
    ["TIMS3", "TIM"],
    ["CSAN3", "Cosan"],
    ["UGPA3", "Ultrapar"],
    ["HYPE3", "Hypera"],
    ["NTCO3", "Natura"],
    ["PCAR3", "Grupo Pão de Açúcar"],
    ["CPLE6", "Copel PNB"],
    ["EGIE3", "Engie Brasil"],
    ["YDUQ3", "Yduqs"],
    ["COGN3", "Cogna"],
    ["FLRY3", "Fleury"],
    ["QUAL3", "Qualicorp"],
    ["MULT3", "Multiplan"],
    ["BRML3", "BR Malls"],
    ["IGTI11", "Iguatemi"],
  ],
  bdrs: [
    ["AAPL34", "Apple BDR"],
    ["MSFT34", "Microsoft BDR"],
    ["GOGL34", "Alphabet (Google) BDR"],
    ["AMZO34", "Amazon BDR"],
    ["TSLA34", "Tesla BDR"],
    ["NVDA34", "NVIDIA BDR"],
    ["DISB34", "Disney BDR"],
    ["NFLX34", "Netflix BDR"],
    ["FBOK34", "Meta (Facebook) BDR"],
    ["MELI34", "Mercado Livre BDR"],
    ["BABA34", "Alibaba BDR"],
    ["JPMC34", "JPMorgan BDR"],
    ["VISA34", "Visa BDR"],
    ["MSCD34", "Mastercard BDR"],
    ["COCA34", "Coca-Cola BDR"],
    ["MCDC34", "McDonald's BDR"],
    ["NIKE34", "Nike BDR"],
    ["BOAC34", "Bank of America BDR"],
  ],
  etfs: [
    ["BOVA11", "iShares Ibovespa"],
    ["IVVB11", "iShares S&P 500"],
    ["SMAL11", "iShares Small Cap"],
    ["HASH11", "Hashdex Nasdaq Crypto"],
    ["TECK11", "ETF Tech"],
    ["DIVO11", "ETF Dividendos"],
    ["ECOO11", "ETF ESG"],
    ["FIND11", "ETF Financeiro"],
    ["MATB11", "ETF Materiais Básicos"],
    ["SPXI11", "ETF S&P 500"],
  ],
  fiis: [
    ["HGLG11", "CSHG Logística"],
    ["KNRI11", "Kinea Renda Imobiliária"],
    ["HGRE11", "CSHG Real Estate"],
    ["MXRF11", "Maxi Renda"],
    ["VISC11", "Vinci Shopping"],
    ["XPLG11", "XP Log"],
    ["BTLG11", "BTG Pactual Logística"],
    ["HGRU11", "CSHG Renda Urbana"],
    ["VILG11", "Vinci Logística"],
    ["KNCR11", "Kinea Recebíveis"],
    ["XPML11", "XP Malls"],
    ["RBRR11", "RBR Recebíveis"],
    ["HGCR11", "CSHG Recebíveis Imobiliários"],
    ["XPCM11", "XP Crédito Imobiliário"],
  ],
  us: [
    ["AAPL", "Apple"],
    ["MSFT", "Microsoft"],
    ["GOOGL", "Alphabet Class A"],
    ["GOOG", "Alphabet Class C"],
    ["AMZN", "Amazon"],
    ["META", "Meta Platforms"],
    ["TSLA", "Tesla"],
    ["NVDA", "NVIDIA"],
    ["AMD", "AMD"],
    ["INTC", "Intel"],
    ["NFLX", "Netflix"],
    ["DIS", "Disney"],
    ["V", "Visa"],
    ["MA", "Mastercard"],
    ["JPM", "JPMorgan"],
    ["BAC", "Bank of America"],
    ["GS", "Goldman Sachs"],
    ["MS", "Morgan Stanley"],
    ["KO", "Coca-Cola"],
    ["PEP", "PepsiCo"],
    ["MCD", "McDonald's"],
    ["SBUX", "Starbucks"],
    ["NKE", "Nike"],
    ["WMT", "Walmart"],
    ["HD", "Home Depot"],
    ["BABA", "Alibaba"],
    ["UBER", "Uber"],
    ["ABNB", "Airbnb"],
    ["PYPL", "PayPal"],
    ["SQ", "Block (Square)"],
  ],
  crypto: [
    ["BTC-USD", "Bitcoin"],
    ["ETH-USD", "Ethereum"],
    ["SOL-USD", "Solana"],
    ["BNB-USD", "BNB"],
    ["XRP-USD", "XRP"],
    ["ADA-USD", "Cardano"],
    ["DOGE-USD", "Dogecoin"],
    ["DOT-USD", "Polkadot"],
    ["AVAX-USD", "Avalanche"],
    ["MATIC-USD", "Polygon"],
  ],
  fx: [
    ["USDBRL=X", "Dólar (USD/BRL)"],
    ["EURBRL=X", "Euro (EUR/BRL)"],
    ["GBPBRL=X", "Libra (GBP/BRL)"],
    ["JPYBRL=X", "Iene (JPY/BRL)"],
    ["ARSBRL=X", "Peso Argentino (ARS/BRL)"],
    ["EURUSD=X", "Euro/Dólar"],
    ["GBPUSD=X", "Libra/Dólar"],
  ],
};
